### ISSUE TITLE
FPS and dt are weird

### ISSUE THREAD

**Issue by freemin7** [dalum/Gloria.jl#2]
I played around with the example and noticed 2 things:
 - The FPS value is updated only once per second and not more continuously
 - The dt is always >50 Hz even when simulation chucks in the particle swarm simulation a lot due to inter-particle forces being activated.

**Comment by dalum** [comment]
Thanks for opening an issue!

The FPS and dt values *should* be fixed in the latest version (v0.2.0).  Please let me know if you still find that they aren't. :relaxed:

**Comment by dalum** [comment]
Oops, inspecting it today, it seems that the "fix" I made yesterday made things worse. *Should* been fixed now in v0.2.1.
